### PR TITLE
Add pitchfork on Rack 2.

### PR DESCRIPTION
**Pull request by ioquatix**
Add `pitchfork` server.

## Types of Changes

- New feature.

## Contribution

- [ ] I added tests for my changes.
- [x] I tested my changes locally.
- [x] I agree to the [Developer's Certificate of Origin 1.1](https://developercertificate.org/).

### CODE REVIEW

**Comment by ioquatix** [comment]
@byroot it looks like pitchfork has some problem with `rack.hijack`.

## Server

To start the test server:

```bash
$ git clone git@github.com:socketry/rack-conform
$ cd rack-conform
$ export BUNDLE_GEMFILE=gems/pitchfork-v0-rack-v2.rb
$ bundle install
$ bundle exec pitchfork -E none
```

## Client

Use curl as a client to show the issue:

```
> curl -v http://localhost:8080/streaming/hijack
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8080...
* connect to ::1 port 8080 from ::1 port 58096 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080
> GET /streaming/hijack HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.8.0
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< Date: Thu, 13 Jun 2024 11:53:16 GMT
< Connection: close
< Transfer-Encoding: chunked
< 
* chunk hex-length char not a hex digit: 0x48
* Illegal or missing hexadecimal sequence in chunked-encoding
* Closing connection
curl: (56) chunk hex-length char not a hex digit: 0x48
```

I took a quick look. I think what's going on is `Pitchfork::Chunked` is applied to the response headers (and body) but the body is not wrapped, because the result of partial hijack is returned via the response headers. 

Are you able to investigate? (this test passes on unicorn & every other server FYI).

**Comment by byroot** [comment]
See: https://github.com/Shopify/pitchfork/issues/130

**Comment by ioquatix** [comment]
Serendipity :)

**Comment by byroot** [comment]
And as noticed @Earlopain, Unicorn only passes because it's ran without the default middlewares, which usually isn't how it's ran in production.

**Comment by Earlopain** [comment]
This is probably only anecdotal evidence but I've had `RACK_ENV` set to `production` with unicorn since forever, mirroring what `RAILS_ENV` accepts. Turns out I've been running without these middleswares (except of course what rails inserts by default, there is some overlap) without realizing.

**Comment by ioquatix** [comment]
> This is probably only anecdotal evidence but I've had RACK_ENV set to production with unicorn (it requires deployment) since forever, mirroring what RAILS_ENV accepts. Turns out I've been running without these middleswares (except of course what rails inserts by default, there is some overlap) without realizing.

This is not your fault and one of the reasons why I'm in favour of and have been slowly removing `RACK_ENV`. The first step was to remove `RACK_ENV` from `rack` itself, and it only exists in `rackup` now. It's an extremely confusing environment variable that probably never should have existed.

**Comment by ioquatix** [comment]
See <https://github.com/socketry/rack-conform/pull/21> for additional context.

**Pull request merged**
